name: timetable_example
description: A simple example app for the timetable package
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  debug_overlay: ^0.2.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  timetable:
    path: ../
  web: ^0.5.1

dev_dependencies:
  flutter_lints: ^2.0.3

dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
